services:
  auth-service:
    depends_on:
      - redis
    build: ./authentication/
    ports:
      - "8000:8080"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

